name: py4at
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy
  - pandas
  - matplotlib
  - scikit-learn
  - jupyterlab
  - requests
  - pandas-datareader
  - pip
  - pip:
      - yfinance
      - tables